name: Deploy Frontend to QA

on:
  push:
    branches:
      - main
      

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend on QA server
        run: |
          set -e

          cd /home/karthik

          if [ ! -d "Logistic-Management-System-Frontend" ]; then
            git clone git@github.com:saichithra123/logistics-management.git Logistic-Management-System-Frontend
          fi

          cd Logistic-Management-System-Frontend

          git fetch origin
          git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}

          docker stop logistics-frontend || true
          docker rm logistics-frontend || true

          docker build -t logistics-frontend .
          docker run -d --name logistics-frontend -p 3000:80 logistics-frontend
